FROM registry.cn-hangzhou.aliyuncs.com/catshop/catshop:commerce

RUN composer require "drupal/core:8.4.3" \
                    "drupal/facets:1.x-dev" \
                    "drupal/devel:1.x-dev" \
                    "drupal/default_content" \
                    "drupal/file_entity:2.x-dev" \
                    "drupal/restui" \
                    "drupal/simple_oauth" \
                    "drupal/openapi" \
                    "drupal/erd" \
                    "drupal/commerce_shipping"
