<?php
/**
 * Created by PhpStorm.
 * User: kent
 * Date: 2017/11/10
 * Time: 13:41
 */

use Drupal\commerce_product\Entity\ProductType;
use Drupal\commerce_product\Entity\ProductVariationType;
use Drupal\commerce\BundleFieldDefinition;
use Drupal\commerce\Entity\CommerceBundleEntityInterface;

/**
 * Implements hook_entity_bundle_create().
 */
function catshop_entity_bundle_create($entity_type_id, $bundle) {

    switch ($entity_type_id) {
        case 'commerce_product':
            catshop_product_add_image_field(ProductType::load($bundle), 'commerce_product');
            break;
        case 'commerce_product_variation':
            catshop_product_add_image_field(ProductVariationType::load($bundle), 'commerce_product_variation');
            break;
    }
}

/**
 * Adds the default image field to a CommerceBundleEntity.
 *
 * @param \Drupal\commerce\Entity\CommerceBundleEntityInterface $entity
 *   The product type.
 * @param $target_entity_type_id
 * @internal param string $label (optional) The label for the body instance. Defaults to 'Body'.*   (optional) The label for the body instance. Defaults to 'Body'.
 */
function catshop_product_add_image_field(CommerceBundleEntityInterface $entity, $target_entity_type_id) {
    $field_definition = BundleFieldDefinition::create('image')
        ->setTargetEntityTypeId($target_entity_type_id)
        ->setTargetBundle($entity->id())
        ->setName('image')
        ->setLabel(t('Image'))
        ->setRequired(true)
        ->setTranslatable(false)
        ->setSettings([
            'file_directory'=>'product_image/[date:custom:Y]-[date:custom:m]',
            'file_extensions'=>'png gif jpg jpeg',
            'max_filesize'=>'200KB',
            'max_resolution'=>'422x535',
            'min_resolution'=>'422x535',
            'alt_field'=> false,
            'alt_field_required'=> true,
            'title_field'=> false,
            'title_field_required'=> true,
            'default_image'=>[
                'uuid'=> '',
                'alt'=> '',
                'title'=> '',
                'width'=> null,
                'height'=> null
            ],
            'handler'=> 'default:file',
            'handler_settings'=>[]
        ])
        ->setDisplayOptions('form', [
            'weight' => 2,
            'type' => 'image_image',
            'region'=> 'content',
            'settings'=>[
                'progress_indicator'=> 'throbber',
                'preview_image_style'=> 'thumbnail'
            ],

        ])
        ->setDisplayOptions('view', [
            'weight' => 0,
            'label' => 'above',
            'type' => 'image',
            'region'=> 'content'
        ]);

    $configurable_field_manager = \Drupal::service('commerce.configurable_field_manager');
    $configurable_field_manager->createField($field_definition, FALSE);
}