<?php
/**
 * Created by PhpStorm.
 * User: kent
 * Date: 2017/11/10
 * Time: 13:41
 */

use Drupal\commerce_product\Entity\HotelType;
use Drupal\commerce_product\Entity\ProductVariationType;
use Drupal\commerce\BundleFieldDefinition;
use Drupal\commerce\Entity\CommerceBundleEntityInterface;
use Drupal\commerce_product\Entity\ProductTypeInterface;

/**
 * Implements hook_entity_bundle_create().
 */
function catshop_entity_bundle_create($entity_type_id, $bundle) {

    switch ($entity_type_id) {
        case 'commerce_product':
            $product_type = HotelType::load($bundle);
            catshop_product_add_image_field($product_type, $entity_type_id);
            catshop_product_add_categories_field($product_type);
            catshop_product_add_brand_field($product_type);
            break;
        case 'commerce_product_variation':
            catshop_product_add_image_field(ProductVariationType::load($bundle), $entity_type_id);
            break;
    }
}

/**
 * Adds the default image field to a CommerceBundleEntity.
 *
 * @param \Drupal\commerce\Entity\CommerceBundleEntityInterface $entity
 *   The product type.
 * @param $target_entity_type_id
 * @internal param string $label (optional) The label for the body instance. Defaults to 'Body'.*   (optional) The label for the body instance. Defaults to 'Body'.
 */
function catshop_product_add_image_field(CommerceBundleEntityInterface $entity, $target_entity_type_id) {
    $field_definition = BundleFieldDefinition::create('image')
        ->setTargetEntityTypeId($target_entity_type_id)
        ->setTargetBundle($entity->id())
        ->setName('image')
        ->setLabel(t('Image'))
        ->setRequired(true)
        ->setTranslatable(false)
        ->setSettings([
            'file_directory'=>'product_image/[date:custom:Y]-[date:custom:m]',
            'file_extensions'=>'png gif jpg jpeg',
            'max_filesize'=>'200KB',
            'max_resolution'=>'422x535',
            'min_resolution'=>'422x535',
            'alt_field'=> false,
            'alt_field_required'=> true,
            'title_field'=> false,
            'title_field_required'=> true,
            'default_image'=>[
                'uuid'=> '',
                'alt'=> '',
                'title'=> '',
                'width'=> null,
                'height'=> null
            ],
            'handler'=> 'default:file',
            'handler_settings'=>[]
        ])
        ->setDisplayOptions('form', [
            'weight' => 2,
            'type' => 'image_image',
            'region'=> 'content',
            'settings'=>[
                'progress_indicator'=> 'throbber',
                'preview_image_style'=> 'thumbnail'
            ],

        ])
        ->setDisplayOptions('view', [
            'weight' => 0,
            'label' => 'above',
            'type' => 'image',
            'region'=> 'content'
        ]);

    $configurable_field_manager = \Drupal::service('commerce.configurable_field_manager');
    $configurable_field_manager->createField($field_definition, FALSE);
}

/**
 * Adds the default categories field to a product.
 *
 * A product can belong to multiple categories.
 *
 * @param \Drupal\commerce_product\Entity\ProductTypeInterface $product_type
 *   The product type.
 */
function catshop_product_add_categories_field(ProductTypeInterface $product_type) {
    $field_definition = BundleFieldDefinition::create('entity_reference')
        ->setTargetEntityTypeId('commerce_product')
        ->setTargetBundle($product_type->id())
        ->setName('categories')
        ->setLabel('Categories')
        ->setCardinality(BundleFieldDefinition::CARDINALITY_UNLIMITED)
        ->setRequired(false)
        ->setSetting('target_type', 'taxonomy_term')
        ->setSetting('handler', 'default')
        ->setDisplayOptions('form', [
            'type' => 'entity_reference_autocomplete',
            'weight' => 50,
        ]);

    $configurable_field_manager = \Drupal::service('commerce.configurable_field_manager');
    $configurable_field_manager->createField($field_definition);
}

/**
 * Adds the default brand field to a product.
 *
 * A product only can belong to one brand.
 *
 * @param \Drupal\commerce_product\Entity\ProductTypeInterface $product_type
 *   The product type.
 */
function catshop_product_add_brand_field(ProductTypeInterface $product_type) {
    $field_definition = BundleFieldDefinition::create('entity_reference')
        ->setTargetEntityTypeId('commerce_product')
        ->setTargetBundle($product_type->id())
        ->setName('brand')
        ->setLabel('Brand')
        ->setCardinality(1)
        ->setRequired(false)
        ->setSetting('target_type', 'taxonomy_term')
        ->setSetting('handler', 'default')
        ->setDisplayOptions('form', [
            'type' => 'entity_reference_autocomplete',
            'weight' => 51,
        ]);

    $configurable_field_manager = \Drupal::service('commerce.configurable_field_manager');
    $configurable_field_manager->createField($field_definition);
}